In [4]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 1.8 MB/s eta 0:00:0000:0100:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

In [5]:
import pandas as pd
dataset = pd.read_csv("../raw/card_transdata.csv")
dataset = dataset[(dataset['distance_from_home'] < 15000) & (dataset['used_pin_number'] == 1) | (dataset['used_chip'] == 1) ]
midpoint = len(dataset) // 65
dataset = dataset.iloc[:midpoint]
data_filtered = dataset.dropna(subset=['distance_from_home'])
data_filtered = pd.DataFrame(data_filtered)
df = data_filtered.dropna(axis=1, how='any')
bins = pd.cut(df["distance_from_home"], bins=10)
df_byrange = df.groupby(bins).mean()
df_byrange

/var/folders/f0/nh99jdt16ddg2nsr3t4x3s7r0000gn/T/ipykernel_97523/1722215369.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv("../raw/card_transdata.csv")

,distance_from_home,distance_from_last_transaction,ratio_to_median_purchase_price,repeat_retailer,used_chip,used_pin_number,online_order,fraud
distance_from_home,,,,,,,,
"(-0.984, 105.889]",17.190794,4.661810,1.875749,0.871121,0.837426,0.242909,0.640206,0.050828
"(105.889, 211.705]",142.993671,4.960914,1.699493,1.000000,0.841176,0.252941,0.682353,0.041176
"(211.705, 317.521]",260.020279,3.225742,1.607308,1.000000,0.814815,0.277778,0.666667,0.111111
"(317.521, 423.336]",364.072644,5.762234,2.765827,1.000000,0.869565,0.260870,0.652174,0.086957
"(423.336, 529.152]",468.476258,1.735081,1.907544,1.000000,0.500000,0.750000,0.750000,0.000000
"(529.152, 634.967]",567.552626,1.955548,0.837979,1.000000,1.000000,0.200000,0.800000,0.000000
"(634.967, 740.783]",688.583703,7.008391,0.536255,1.000000,1.000000,0.333333,1.000000,0.000000
"(740.783, 846.599]",763.384174,0.354975,1.023965,1.000000,1.000000,0.000000,0.000000,0.000000
"(846.599, 952.414]",889.541493,0.435840,0.884502,1.000000,1.000000,0.000000,0.000000,0.000000
"(952.414, 1058.23]",1030.241353,3.602288,1.613256,1.000000,1.000000,0.500000,1.000000,0.000000

In [6]:
df_byrange.to_excel('table.xlsx', index=False)